language: node_js
node_js:
  - "8"
  - "9"
  - "10"
addons:
  chrome: stable
sudo: require
before_script:
  - "sudo chown root /opt/google/chrome-sandbox"
  - "sudo chown root 4755 /opt/google/chrome/chrome-sandbox"
